package cs371m.csc2726.busbuddy;

import android.graphics.Color;

import java.util.Random;

/**
 * Created by witchel on 1/30/2018.
 */

// Colors from Name that Color javascript http://chir.ag/projects/ntc/
public class ColorDict {
    static class ColorName {
        int color;
        String name;
        ColorName(int i, String s) {
            this.color = Color.rgb(((i>>16)&0xFF),((i>>8)&0xFF), (i&0xFF));
            this.name = s;
        }
    }
    public static int randomSwap(Random random, int position) {
        ColorDict.ColorName temp;
        if( dict.length <= 1 ) return 0;
        int index = random.nextInt(dict.length);
        while( index == position ) {
            index = random.nextInt(dict.length);
        }
        temp = dict[index];
        dict[index] = dict[position];
        dict[position] = temp;
        return index;
    }
    public static void shuffleArray() {
        Random random = new Random();
        for (int i = dict.length - 1; i > 0; i--) {
            randomSwap(random, i);
        }
    }

    static ColorName[] dict = {
            new ColorName(0x000000, "Black"),
            new ColorName(0x000080, "Navy Blue"),
            new ColorName(0x0000C8, "Dark Blue"),
            new ColorName(0x0000FF, "Blue"),
            new ColorName(0x000741, "Stratos"),
            new ColorName(0x001B1C, "Swamp"),
            new ColorName(0x002387, "Resolution Blue"),
            new ColorName(0x002900, "Deep Fir"),
            new ColorName(0x002E20, "Burnham"),
            new ColorName(0x002FA7, "International Klein Blue"),
            new ColorName(0x003153, "Prussian Blue"),
            new ColorName(0x003366, "Midnight Blue"),
            new ColorName(0x003399, "Smalt"),
            new ColorName(0x003532, "Deep Teal"),
            new ColorName(0x003E40, "Cyprus"),
            new ColorName(0x004620, "Kaitoke Green"),
            new ColorName(0x0047AB, "Cobalt"),
            new ColorName(0x004816, "Crusoe"),
            new ColorName(0x004950, "Sherpa Blue"),
            new ColorName(0x0056A7, "Endeavour"),
            new ColorName(0x00581A, "Camarone"),
            new ColorName(0x0066CC, "Science Blue"),
            new ColorName(0x0066FF, "Blue Ribbon"),
            new ColorName(0x00755E, "Tropical Rain Forest"),
            new ColorName(0x0076A3, "Allports"),
            new ColorName(0x007BA7, "Deep Cerulean"),
            new ColorName(0x007EC7, "Lochmara"),
            new ColorName(0x007FFF, "Azure Radiance"),
            new ColorName(0x008080, "Teal"),
            new ColorName(0x0095B6, "Bondi Blue"),
            new ColorName(0x009DC4, "Pacific Blue"),
            new ColorName(0x00A693, "Persian Green"),
            new ColorName(0x00A86B, "Jade"),
            new ColorName(0x00CC99, "Caribbean Green"),
            new ColorName(0x00CCCC, "Robin's Egg Blue"),
            new ColorName(0x00FF00, "Green"),
            new ColorName(0x00FF7F, "Spring Green"),
            new ColorName(0x00FFFF, "Cyan / Aqua"),
            new ColorName(0x010D1A, "Blue Charcoal"),
            new ColorName(0x011635, "Midnight"),
            new ColorName(0x011D13, "Holly"),
            new ColorName(0x012731, "Daintree"),
            new ColorName(0x01361C, "Cardin Green"),
            new ColorName(0x01371A, "County Green"),
            new ColorName(0x013E62, "Astronaut Blue"),
            new ColorName(0x013F6A, "Regal Blue"),
            new ColorName(0x014B43, "Aqua Deep"),
            new ColorName(0x015E85, "Orient"),
            new ColorName(0x016162, "Blue Stone"),
            new ColorName(0x016D39, "Fun Green"),
            new ColorName(0x01796F, "Pine Green"),
            new ColorName(0x017987, "Blue Lagoon"),
            new ColorName(0x01826B, "Deep Sea"),
            new ColorName(0x01A368, "Green Haze"),
            new ColorName(0x022D15, "English Holly"),
            new ColorName(0x02402C, "Sherwood Green"),
            new ColorName(0x02478E, "Congress Blue"),
            new ColorName(0x024E46, "Evening Sea"),
            new ColorName(0x026395, "Bahama Blue"),
            new ColorName(0x02866F, "Observatory"),
            new ColorName(0x02A4D3, "Cerulean"),
            new ColorName(0x03163C, "Tangaroa"),
            new ColorName(0x032B52, "Green Vogue"),
            new ColorName(0x036A6E, "Mosque"),
            new ColorName(0x041004, "Midnight Moss"),
            new ColorName(0x041322, "Black Pearl"),
            new ColorName(0x042E4C, "Blue Whale"),
            new ColorName(0x044022, "Zuccini"),
            new ColorName(0x044259, "Teal Blue"),
            new ColorName(0x051040, "Deep Cove"),
            new ColorName(0x051657, "Gulf Blue"),
            new ColorName(0x055989, "Venice Blue"),
            new ColorName(0x056F57, "Watercourse"),
            new ColorName(0x062A78, "Catalina Blue"),
            new ColorName(0x063537, "Tiber"),
            new ColorName(0x069B81, "Gossamer"),
            new ColorName(0x06A189, "Niagara"),
            new ColorName(0x073A50, "Tarawera"),
            new ColorName(0x080110, "Jaguar"),
            new ColorName(0x081910, "Black Bean"),
            new ColorName(0x082567, "Deep Sapphire"),
            new ColorName(0x088370, "Elf Green"),
            new ColorName(0x08E8DE, "Bright Turquoise"),
            new ColorName(0x092256, "Downriver"),
            new ColorName(0x09230F, "Palm Green"),
            new ColorName(0x09255D, "Madison"),
            new ColorName(0x093624, "Bottle Green"),
            new ColorName(0x095859, "Deep Sea Green"),
            new ColorName(0x097F4B, "Salem"),
            new ColorName(0x0A001C, "Black Russian"),
            new ColorName(0x0A480D, "Dark Fern"),
            new ColorName(0x0A6906, "Japanese Laurel"),
            new ColorName(0x0A6F75, "Atoll"),
            new ColorName(0x0B0B0B, "Cod Gray"),
            new ColorName(0x0B0F08, "Marshland"),
            new ColorName(0x0B1107, "Gordons Green"),
            new ColorName(0x0B1304, "Black Forest"),
            new ColorName(0x0B6207, "San Felix"),
            new ColorName(0x0BDA51, "Malachite"),
            new ColorName(0x0C0B1D, "Ebony"),
            new ColorName(0x0C0D0F, "Woodsmoke"),
            new ColorName(0x0C1911, "Racing Green"),
            new ColorName(0x0C7A79, "Surfie Green"),
            new ColorName(0x0C8990, "Blue Chill"),
            new ColorName(0x0D0332, "Black Rock"),
            new ColorName(0x0D1117, "Bunker"),
            new ColorName(0x0D1C19, "Aztec"),
            new ColorName(0x0D2E1C, "Bush"),
            new ColorName(0x0E0E18, "Cinder"),
            new ColorName(0x0E2A30, "Firefly"),
            new ColorName(0x0F2D9E, "Torea Bay"),
            new ColorName(0x10121D, "Vulcan"),
            new ColorName(0x101405, "Green Waterloo"),
            new ColorName(0x105852, "Eden"),
            new ColorName(0x110C6C, "Arapawa"),
            new ColorName(0x120A8F, "Ultramarine"),
            new ColorName(0x123447, "Elephant"),
            new ColorName(0x126B40, "Jewel"),
            new ColorName(0x130000, "Diesel"),
            new ColorName(0x130A06, "Asphalt"),
            new ColorName(0x13264D, "Blue Zodiac"),
            new ColorName(0x134F19, "Parsley"),
            new ColorName(0x140600, "Nero"),
            new ColorName(0x1450AA, "Tory Blue"),
            new ColorName(0x151F4C, "Bunting"),
            new ColorName(0x1560BD, "Denim"),
            new ColorName(0x15736B, "Genoa"),
            new ColorName(0x161928, "Mirage"),
            new ColorName(0x161D10, "Hunter Green"),
            new ColorName(0x162A40, "Big Stone"),
            new ColorName(0x163222, "Celtic"),
            new ColorName(0x16322C, "Timber Green"),
            new ColorName(0x163531, "Gable Green"),
            new ColorName(0x171F04, "Pine Tree"),
            new ColorName(0x175579, "Chathams Blue"),
            new ColorName(0x182D09, "Deep Forest Green"),
            new ColorName(0x18587A, "Blumine"),
            new ColorName(0x19330E, "Palm Leaf"),
            new ColorName(0x193751, "Nile Blue"),
            new ColorName(0x1959A8, "Fun Blue"),
            new ColorName(0x1A1A68, "Lucky Point"),
            new ColorName(0x1AB385, "Mountain Meadow"),
            new ColorName(0x1B0245, "Tolopea"),
            new ColorName(0x1B1035, "Haiti"),
            new ColorName(0x1B127B, "Deep Koamaru"),
            new ColorName(0x1B1404, "Acadia"),
            new ColorName(0x1B2F11, "Seaweed"),
            new ColorName(0x1B3162, "Biscay"),
            new ColorName(0x1B659D, "Matisse"),
            new ColorName(0x1C1208, "Crowshead"),
            new ColorName(0x1C1E13, "Rangoon Green"),
            new ColorName(0x1C39BB, "Persian Blue"),
            new ColorName(0x1C402E, "Everglade"),
            new ColorName(0x1C7C7D, "Elm"),
            new ColorName(0x1D6142, "Green Pea"),
            new ColorName(0x1E0F04, "Creole"),
            new ColorName(0x1E1609, "Karaka"),
            new ColorName(0x1E1708, "El Paso"),
            new ColorName(0x1E385B, "Cello"),
            new ColorName(0x1E433C, "Te Papa Green"),
            new ColorName(0x1E90FF, "Dodger Blue"),
            new ColorName(0x1E9AB0, "Eastern Blue"),
            new ColorName(0x1F120F, "Night Rider"),
            new ColorName(0x1FC2C2, "Java"),
            new ColorName(0x20208D, "Jacksons Purple"),
            new ColorName(0x202E54, "Cloud Burst"),
            new ColorName(0x204852, "Blue Dianne"),
            new ColorName(0x211A0E, "Eternity"),
            new ColorName(0x220878, "Deep Blue"),
            new ColorName(0x228B22, "Forest Green"),
            new ColorName(0x233418, "Mallard"),
            new ColorName(0x240A40, "Violet"),
            new ColorName(0x240C02, "Kilamanjaro"),
            new ColorName(0x242A1D, "Log Cabin"),
            new ColorName(0x242E16, "Black Olive"),
            new ColorName(0x24500F, "Green House"),
            new ColorName(0x251607, "Graphite"),
            new ColorName(0x251706, "Cannon Black"),
            new ColorName(0x251F4F, "Port Gore"),
            new ColorName(0x25272C, "Shark"),
            new ColorName(0x25311C, "Green Kelp"),
            new ColorName(0x2596D1, "Curious Blue"),
            new ColorName(0x260368, "Paua"),
            new ColorName(0x26056A, "Paris M"),
            new ColorName(0x261105, "Wood Bark"),
            new ColorName(0x261414, "Gondola"),
            new ColorName(0x262335, "Steel Gray"),
            new ColorName(0x26283B, "Ebony Clay"),
            new ColorName(0x273A81, "Bay of Many"),
            new ColorName(0x27504B, "Plantation"),
            new ColorName(0x278A5B, "Eucalyptus"),
            new ColorName(0x281E15, "Oil"),
            new ColorName(0x283A77, "Astronaut"),
            new ColorName(0x286ACD, "Mariner"),
            new ColorName(0x290C5E, "Violent Violet"),
            new ColorName(0x292130, "Bastille"),
            new ColorName(0x292319, "Zeus"),
            new ColorName(0x292937, "Charade"),
            new ColorName(0x297B9A, "Jelly Bean"),
            new ColorName(0x29AB87, "Jungle Green"),
            new ColorName(0x2A0359, "Cherry Pie"),
            new ColorName(0x2A140E, "Coffee Bean"),
            new ColorName(0x2A2630, "Baltic Sea"),
            new ColorName(0x2A380B, "Turtle Green"),
            new ColorName(0x2A52BE, "Cerulean Blue"),
            new ColorName(0x2B0202, "Sepia Black"),
            new ColorName(0x2B194F, "Valhalla"),
            new ColorName(0x2B3228, "Heavy Metal"),
            new ColorName(0x2C0E8C, "Blue Gem"),
            new ColorName(0x2C1632, "Revolver"),
            new ColorName(0x2C2133, "Bleached Cedar"),
            new ColorName(0x2C8C84, "Lochinvar"),
            new ColorName(0x2D2510, "Mikado"),
            new ColorName(0x2D383A, "Outer Space"),
            new ColorName(0x2D569B, "St Tropaz"),
            new ColorName(0x2E0329, "Jacaranda"),
            new ColorName(0x2E1905, "Jacko Bean"),
            new ColorName(0x2E3222, "Rangitoto"),
            new ColorName(0x2E3F62, "Rhino"),
            new ColorName(0x2E8B57, "Sea Green"),
            new ColorName(0x2EBFD4, "Scooter"),
            new ColorName(0x2F270E, "Onion"),
            new ColorName(0x2F3CB3, "Governor Bay"),
            new ColorName(0x2F519E, "Sapphire"),
            new ColorName(0x2F5A57, "Spectra"),
            new ColorName(0x2F6168, "Casal"),
            new ColorName(0x300529, "Melanzane"),
            new ColorName(0x301F1E, "Cocoa Brown"),
            new ColorName(0x302A0F, "Woodrush"),
            new ColorName(0x304B6A, "San Juan"),
            new ColorName(0x30D5C8, "Turquoise"),
            new ColorName(0x311C17, "Eclipse"),
            new ColorName(0x314459, "Pickled Bluewood"),
            new ColorName(0x315BA1, "Azure"),
            new ColorName(0x31728D, "Calypso"),
            new ColorName(0x317D82, "Paradiso"),
            new ColorName(0x32127A, "Persian Indigo"),
            new ColorName(0x32293A, "Blackcurrant"),
            new ColorName(0x323232, "Mine Shaft"),
            new ColorName(0x325D52, "Stromboli"),
            new ColorName(0x327C14, "Bilbao"),
            new ColorName(0x327DA0, "Astral"),
            new ColorName(0x33036B, "Christalle"),
            new ColorName(0x33292F, "Thunder"),
            new ColorName(0x33CC99, "Shamrock"),
            new ColorName(0x341515, "Tamarind"),
            new ColorName(0x350036, "Mardi Gras"),
            new ColorName(0x350E42, "Valentino"),
            new ColorName(0x350E57, "Jagger"),
            new ColorName(0x353542, "Tuna"),
            new ColorName(0x354E8C, "Chambray"),
            new ColorName(0x363050, "Martinique"),
            new ColorName(0x363534, "Tuatara"),
            new ColorName(0x363C0D, "Waiouru"),
            new ColorName(0x36747D, "Ming"),
            new ColorName(0x368716, "La Palma"),
            new ColorName(0x370202, "Chocolate"),
            new ColorName(0x371D09, "Clinker"),
            new ColorName(0x37290E, "Brown Tumbleweed"),
            new ColorName(0x373021, "Birch"),
            new ColorName(0x377475, "Oracle"),
            new ColorName(0x380474, "Blue Diamond"),
            new ColorName(0x381A51, "Grape"),
            new ColorName(0x383533, "Dune"),
            new ColorName(0x384555, "Oxford Blue"),
            new ColorName(0x384910, "Clover"),
            new ColorName(0x394851, "Limed Spruce"),
            new ColorName(0x396413, "Dell"),
            new ColorName(0x3A0020, "Toledo"),
            new ColorName(0x3A2010, "Sambuca"),
            new ColorName(0x3A2A6A, "Jacarta"),
            new ColorName(0x3A686C, "William"),
            new ColorName(0x3A6A47, "Killarney"),
            new ColorName(0x3AB09E, "Keppel"),
            new ColorName(0x3B000B, "Temptress"),
            new ColorName(0x3B0910, "Aubergine"),
            new ColorName(0x3B1F1F, "Jon"),
            new ColorName(0x3B2820, "Treehouse"),
            new ColorName(0x3B7A57, "Amazon"),
            new ColorName(0x3B91B4, "Boston Blue"),
            new ColorName(0x3C0878, "Windsor"),
            new ColorName(0x3C1206, "Rebel"),
            new ColorName(0x3C1F76, "Meteorite"),
            new ColorName(0x3C2005, "Dark Ebony"),
            new ColorName(0x3C3910, "Camouflage"),
            new ColorName(0x3C4151, "Bright Gray"),
            new ColorName(0x3C4443, "Cape Cod"),
            new ColorName(0x3C493A, "Lunar Green"),
            new ColorName(0x3D0C02, "Bean  "),
            new ColorName(0x3D2B1F, "Bistre"),
            new ColorName(0x3D7D52, "Goblin"),
            new ColorName(0x3E0480, "Kingfisher Daisy"),
            new ColorName(0x3E1C14, "Cedar"),
            new ColorName(0x3E2B23, "English Walnut"),
            new ColorName(0x3E2C1C, "Black Marlin"),
            new ColorName(0x3E3A44, "Ship Gray"),
            new ColorName(0x3EABBF, "Pelorous"),
            new ColorName(0x3F2109, "Bronze"),
            new ColorName(0x3F2500, "Cola"),
            new ColorName(0x3F3002, "Madras"),
            new ColorName(0x3F307F, "Minsk"),
            new ColorName(0x3F4C3A, "Cabbage Pont"),
            new ColorName(0x3F583B, "Tom Thumb"),
            new ColorName(0x3F5D53, "Mineral Green"),
            new ColorName(0x3FC1AA, "Puerto Rico"),
            new ColorName(0x3FFF00, "Harlequin"),
            new ColorName(0x401801, "Brown Pod"),
            new ColorName(0x40291D, "Cork"),
            new ColorName(0x403B38, "Masala"),
            new ColorName(0x403D19, "Thatch Green"),
            new ColorName(0x405169, "Fiord"),
            new ColorName(0x40826D, "Viridian"),
            new ColorName(0x40A860, "Chateau Green"),
            new ColorName(0x410056, "Ripe Plum"),
            new ColorName(0x411F10, "Paco"),
            new ColorName(0x412010, "Deep Oak"),
            new ColorName(0x413C37, "Merlin"),
            new ColorName(0x414257, "Gun Powder"),
            new ColorName(0x414C7D, "East Bay"),
            new ColorName(0x4169E1, "Royal Blue"),
            new ColorName(0x41AA78, "Ocean Green"),
            new ColorName(0x420303, "Burnt Maroon"),
            new ColorName(0x423921, "Lisbon Brown"),
            new ColorName(0x427977, "Faded Jade"),
            new ColorName(0x431560, "Scarlet Gum"),
            new ColorName(0x433120, "Iroko"),
            new ColorName(0x433E37, "Armadillo"),
            new ColorName(0x434C59, "River Bed"),
            new ColorName(0x436A0D, "Green Leaf"),
            new ColorName(0x44012D, "Barossa"),
            new ColorName(0x441D00, "Morocco Brown"),
            new ColorName(0x444954, "Mako"),
            new ColorName(0x454936, "Kelp"),
            new ColorName(0x456CAC, "San Marino"),
            new ColorName(0x45B1E8, "Picton Blue"),
            new ColorName(0x460B41, "Loulou"),
            new ColorName(0x462425, "Crater Brown"),
            new ColorName(0x465945, "Gray Asparagus"),
            new ColorName(0x4682B4, "Steel Blue"),
            new ColorName(0x480404, "Rustic Red"),
            new ColorName(0x480607, "Bulgarian Rose"),
            new ColorName(0x480656, "Clairvoyant"),
            new ColorName(0x481C1C, "Cocoa Bean"),
            new ColorName(0x483131, "Woody Brown"),
            new ColorName(0x483C32, "Taupe"),
            new ColorName(0x49170C, "Van Cleef"),
            new ColorName(0x492615, "Brown Derby"),
            new ColorName(0x49371B, "Metallic Bronze"),
            new ColorName(0x495400, "Verdun Green"),
            new ColorName(0x496679, "Blue Bayoux"),
            new ColorName(0x497183, "Bismark"),
            new ColorName(0x4A2A04, "Bracken"),
            new ColorName(0x4A3004, "Deep Bronze"),
            new ColorName(0x4A3C30, "Mondo"),
            new ColorName(0x4A4244, "Tundora"),
            new ColorName(0x4A444B, "Gravel"),
            new ColorName(0x4A4E5A, "Trout"),
            new ColorName(0x4B0082, "Pigment Indigo"),
            new ColorName(0x4B5D52, "Nandor"),
            new ColorName(0x4C3024, "Saddle"),
            new ColorName(0x4C4F56, "Abbey"),
            new ColorName(0x4D0135, "Blackberry"),
            new ColorName(0x4D0A18, "Cab Sav"),
            new ColorName(0x4D1E01, "Indian Tan"),
            new ColorName(0x4D282D, "Cowboy"),
            new ColorName(0x4D282E, "Livid Brown"),
            new ColorName(0x4D3833, "Rock"),
            new ColorName(0x4D3D14, "Punga"),
            new ColorName(0x4D400F, "Bronzetone"),
            new ColorName(0x4D5328, "Woodland"),
            new ColorName(0x4E0606, "Mahogany"),
            new ColorName(0x4E2A5A, "Bossanova"),
            new ColorName(0x4E3B41, "Matterhorn"),
            new ColorName(0x4E420C, "Bronze Olive"),
            new ColorName(0x4E4562, "Mulled Wine"),
            new ColorName(0x4E6649, "Axolotl"),
            new ColorName(0x4E7F9E, "Wedgewood"),
            new ColorName(0x4EABD1, "Shakespeare"),
            new ColorName(0x4F1C70, "Honey Flower"),
            new ColorName(0x4F2398, "Daisy Bush"),
            new ColorName(0x4F69C6, "Indigo"),
            new ColorName(0x4F7942, "Fern Green"),
            new ColorName(0x4F9D5D, "Fruit Salad"),
            new ColorName(0x4FA83D, "Apple"),
            new ColorName(0x504351, "Mortar"),
            new ColorName(0x507096, "Kashmir Blue"),
            new ColorName(0x507672, "Cutty Sark"),
            new ColorName(0x50C878, "Emerald"),
            new ColorName(0x514649, "Emperor"),
            new ColorName(0x516E3D, "Chalet Green"),
            new ColorName(0x517C66, "Como"),
            new ColorName(0x51808F, "Smalt Blue"),
            new ColorName(0x52001F, "Castro"),
            new ColorName(0x520C17, "Maroon Oak"),
            new ColorName(0x523C94, "Gigas"),
            new ColorName(0x533455, "Voodoo"),
            new ColorName(0x534491, "Victoria"),
            new ColorName(0x53824B, "Hippie Green"),
            new ColorName(0x541012, "Heath"),
            new ColorName(0x544333, "Judge Gray"),
            new ColorName(0x54534D, "Fuscous Gray"),
            new ColorName(0x549019, "Vida Loca"),
            new ColorName(0x55280C, "Cioccolato"),
            new ColorName(0x555B10, "Saratoga"),
            new ColorName(0x556D56, "Finlandia"),
            new ColorName(0x5590D9, "Havelock Blue"),
            new ColorName(0x56B4BE, "Fountain Blue"),
            new ColorName(0x578363, "Spring Leaves"),
            new ColorName(0x583401, "Saddle Brown"),
            new ColorName(0x585562, "Scarpa Flow"),
            new ColorName(0x587156, "Cactus"),
            new ColorName(0x589AAF, "Hippie Blue"),
            new ColorName(0x591D35, "Wine Berry"),
            new ColorName(0x592804, "Brown Bramble"),
            new ColorName(0x593737, "Congo Brown"),
            new ColorName(0x594433, "Millbrook"),
            new ColorName(0x5A6E9C, "Waikawa Gray"),
            new ColorName(0x5A87A0, "Horizon"),
            new ColorName(0x5B3013, "Jambalaya"),
            new ColorName(0x5C0120, "Bordeaux"),
            new ColorName(0x5C0536, "Mulberry Wood"),
            new ColorName(0x5C2E01, "Carnaby Tan"),
            new ColorName(0x5C5D75, "Comet"),
            new ColorName(0x5D1E0F, "Redwood"),
            new ColorName(0x5D4C51, "Don Juan"),
            new ColorName(0x5D5C58, "Chicago"),
            new ColorName(0x5D5E37, "Verdigris"),
            new ColorName(0x5D7747, "Dingley"),
            new ColorName(0x5DA19F, "Breaker Bay"),
            new ColorName(0x5E483E, "Kabul"),
            new ColorName(0x5E5D3B, "Hemlock"),
            new ColorName(0x5F3D26, "Irish Coffee"),
            new ColorName(0x5F5F6E, "Mid Gray"),
            new ColorName(0x5F6672, "Shuttle Gray"),
            new ColorName(0x5FA777, "Aqua Forest"),
            new ColorName(0x5FB3AC, "Tradewind"),
            new ColorName(0x604913, "Horses Neck"),
            new ColorName(0x605B73, "Smoky"),
            new ColorName(0x606E68, "Corduroy"),
            new ColorName(0x6093D1, "Danube"),
            new ColorName(0x612718, "Espresso"),
            new ColorName(0x614051, "Eggplant"),
            new ColorName(0x615D30, "Costa Del Sol"),
            new ColorName(0x61845F, "Glade Green"),
            new ColorName(0x622F30, "Buccaneer"),
            new ColorName(0x623F2D, "Quincy"),
            new ColorName(0x624E9A, "Butterfly Bush"),
            new ColorName(0x625119, "West Coast"),
            new ColorName(0x626649, "Finch"),
            new ColorName(0x639A8F, "Patina"),
            new ColorName(0x63B76C, "Fern"),
            new ColorName(0x6456B7, "Blue Violet"),
            new ColorName(0x646077, "Dolphin"),
            new ColorName(0x646463, "Storm Dust"),
            new ColorName(0x646A54, "Siam"),
            new ColorName(0x646E75, "Nevada"),
            new ColorName(0x6495ED, "Cornflower Blue"),
            new ColorName(0x64CCDB, "Viking"),
            new ColorName(0x65000B, "Rosewood"),
            new ColorName(0x651A14, "Cherrywood"),
            new ColorName(0x652DC1, "Purple Heart"),
            new ColorName(0x657220, "Fern Frond"),
            new ColorName(0x65745D, "Willow Grove"),
            new ColorName(0x65869F, "Hoki"),
            new ColorName(0x660045, "Pompadour"),
            new ColorName(0x660099, "Purple"),
            new ColorName(0x66023C, "Tyrian Purple"),
            new ColorName(0x661010, "Dark Tan"),
            new ColorName(0x66B58F, "Silver Tree"),
            new ColorName(0x66FF00, "Bright Green"),
            new ColorName(0x66FF66, "Screamin' Green"),
            new ColorName(0x67032D, "Black Rose"),
            new ColorName(0x675FA6, "Scampi"),
            new ColorName(0x676662, "Ironside Gray"),
            new ColorName(0x678975, "Viridian Green"),
            new ColorName(0x67A712, "Christi"),
            new ColorName(0x683600, "Nutmeg Wood Finish"),
            new ColorName(0x685558, "Zambezi"),
            new ColorName(0x685E6E, "Salt Box"),
            new ColorName(0x692545, "Tawny Port"),
            new ColorName(0x692D54, "Finn"),
            new ColorName(0x695F62, "Scorpion"),
            new ColorName(0x697E9A, "Lynch"),
            new ColorName(0x6A442E, "Spice"),
            new ColorName(0x6A5D1B, "Himalaya"),
            new ColorName(0x6A6051, "Soya Bean"),
            new ColorName(0x6B2A14, "Hairy Heath"),
            new ColorName(0x6B3FA0, "Royal Purple"),
            new ColorName(0x6B4E31, "Shingle Fawn"),
            new ColorName(0x6B5755, "Dorado"),
            new ColorName(0x6B8BA2, "Bermuda Gray"),
            new ColorName(0x6B8E23, "Olive Drab"),
            new ColorName(0x6C3082, "Eminence"),
            new ColorName(0x6CDAE7, "Turquoise Blue"),
            new ColorName(0x6D0101, "Lonestar"),
            new ColorName(0x6D5E54, "Pine Cone"),
            new ColorName(0x6D6C6C, "Dove Gray"),
            new ColorName(0x6D9292, "Juniper"),
            new ColorName(0x6D92A1, "Gothic"),
            new ColorName(0x6E0902, "Red Oxide"),
            new ColorName(0x6E1D14, "Moccaccino"),
            new ColorName(0x6E4826, "Pickled Bean"),
            new ColorName(0x6E4B26, "Dallas"),
            new ColorName(0x6E6D57, "Kokoda"),
            new ColorName(0x6E7783, "Pale Sky"),
            new ColorName(0x6F440C, "Cafe Royale"),
            new ColorName(0x6F6A61, "Flint"),
            new ColorName(0x6F8E63, "Highland"),
            new ColorName(0x6F9D02, "Limeade"),
            new ColorName(0x6FD0C5, "Downy"),
            new ColorName(0x701C1C, "Persian Plum"),
            new ColorName(0x704214, "Sepia"),
            new ColorName(0x704A07, "Antique Bronze"),
            new ColorName(0x704F50, "Ferra"),
            new ColorName(0x706555, "Coffee"),
            new ColorName(0x708090, "Slate Gray"),
            new ColorName(0x711A00, "Cedar Wood Finish"),
            new ColorName(0x71291D, "Metallic Copper"),
            new ColorName(0x714693, "Affair"),
            new ColorName(0x714AB2, "Studio"),
            new ColorName(0x715D47, "Tobacco Brown"),
            new ColorName(0x716338, "Yellow Metal"),
            new ColorName(0x716B56, "Peat"),
            new ColorName(0x716E10, "Olivetone"),
            new ColorName(0x717486, "Storm Gray"),
            new ColorName(0x718080, "Sirocco"),
            new ColorName(0x71D9E2, "Aquamarine Blue"),
            new ColorName(0x72010F, "Venetian Red"),
            new ColorName(0x724A2F, "Old Copper"),
            new ColorName(0x726D4E, "Go Ben"),
            new ColorName(0x727B89, "Raven"),
            new ColorName(0x731E8F, "Seance"),
            new ColorName(0x734A12, "Raw Umber"),
            new ColorName(0x736C9F, "Kimberly"),
            new ColorName(0x736D58, "Crocodile"),
            new ColorName(0x737829, "Crete"),
            new ColorName(0x738678, "Xanadu"),
            new ColorName(0x74640D, "Spicy Mustard"),
            new ColorName(0x747D63, "Limed Ash"),
            new ColorName(0x747D83, "Rolling Stone"),
            new ColorName(0x748881, "Blue Smoke"),
            new ColorName(0x749378, "Laurel"),
            new ColorName(0x74C365, "Mantis"),
            new ColorName(0x755A57, "Russett"),
            new ColorName(0x7563A8, "Deluge"),
            new ColorName(0x76395D, "Cosmic"),
            new ColorName(0x7666C6, "Blue Marguerite"),
            new ColorName(0x76BD17, "Lima"),
            new ColorName(0x76D7EA, "Sky Blue"),
            new ColorName(0x770F05, "Dark Burgundy"),
            new ColorName(0x771F1F, "Crown of Thorns"),
            new ColorName(0x773F1A, "Walnut"),
            new ColorName(0x776F61, "Pablo"),
            new ColorName(0x778120, "Pacifika"),
            new ColorName(0x779E86, "Oxley"),
            new ColorName(0x77DD77, "Pastel Green"),
            new ColorName(0x780109, "Japanese Maple"),
            new ColorName(0x782D19, "Mocha"),
            new ColorName(0x782F16, "Peanut"),
            new ColorName(0x78866B, "Camouflage Green"),
            new ColorName(0x788A25, "Wasabi"),
            new ColorName(0x788BBA, "Ship Cove"),
            new ColorName(0x78A39C, "Sea Nymph"),
            new ColorName(0x795D4C, "Roman Coffee"),
            new ColorName(0x796878, "Old Lavender"),
            new ColorName(0x796989, "Rum"),
            new ColorName(0x796A78, "Fedora"),
            new ColorName(0x796D62, "Sandstone"),
            new ColorName(0x79DEEC, "Spray"),
            new ColorName(0x7A013A, "Siren"),
            new ColorName(0x7A58C1, "Fuchsia Blue"),
            new ColorName(0x7A7A7A, "Boulder"),
            new ColorName(0x7A89B8, "Wild Blue Yonder"),
            new ColorName(0x7AC488, "De York"),
            new ColorName(0x7B3801, "Red Beech"),
            new ColorName(0x7B3F00, "Cinnamon"),
            new ColorName(0x7B6608, "Yukon Gold"),
            new ColorName(0x7B7874, "Tapa"),
            new ColorName(0x7B7C94, "Waterloo "),
            new ColorName(0x7B8265, "Flax Smoke"),
            new ColorName(0x7B9F80, "Amulet"),
            new ColorName(0x7BA05B, "Asparagus"),
            new ColorName(0x7C1C05, "Kenyan Copper"),
            new ColorName(0x7C7631, "Pesto"),
            new ColorName(0x7C778A, "Topaz"),
            new ColorName(0x7C7B7A, "Concord"),
            new ColorName(0x7C7B82, "Jumbo"),
            new ColorName(0x7C881A, "Trendy Green"),
            new ColorName(0x7CA1A6, "Gumbo"),
            new ColorName(0x7CB0A1, "Acapulco"),
            new ColorName(0x7CB7BB, "Neptune"),
            new ColorName(0x7D2C14, "Pueblo"),
            new ColorName(0x7DA98D, "Bay Leaf"),
            new ColorName(0x7DC8F7, "Malibu"),
            new ColorName(0x7DD8C6, "Bermuda"),
            new ColorName(0x7E3A15, "Copper Canyon"),
            new ColorName(0x7F1734, "Claret"),
            new ColorName(0x7F3A02, "Peru Tan"),
            new ColorName(0x7F626D, "Falcon"),
            new ColorName(0x7F7589, "Mobster"),
            new ColorName(0x7F76D3, "Moody Blue"),
            new ColorName(0x7FFF00, "Chartreuse"),
            new ColorName(0x7FFFD4, "Aquamarine"),
            new ColorName(0x800000, "Maroon"),
            new ColorName(0x800B47, "Rose Bud Cherry"),
            new ColorName(0x801818, "Falu Red"),
            new ColorName(0x80341F, "Red Robin"),
            new ColorName(0x803790, "Vivid Violet"),
            new ColorName(0x80461B, "Russet"),
            new ColorName(0x807E79, "Friar Gray"),
            new ColorName(0x808000, "Olive"),
            new ColorName(0x808080, "Gray"),
            new ColorName(0x80B3AE, "Gulf Stream"),
            new ColorName(0x80B3C4, "Glacier"),
            new ColorName(0x80CCEA, "Seagull"),
            new ColorName(0x81422C, "Nutmeg"),
            new ColorName(0x816E71, "Spicy Pink"),
            new ColorName(0x817377, "Empress"),
            new ColorName(0x819885, "Spanish Green"),
            new ColorName(0x826F65, "Sand Dune"),
            new ColorName(0x828685, "Gunsmoke"),
            new ColorName(0x828F72, "Battleship Gray"),
            new ColorName(0x831923, "Merlot"),
            new ColorName(0x837050, "Shadow"),
            new ColorName(0x83AA5D, "Chelsea Cucumber"),
            new ColorName(0x83D0C6, "Monte Carlo"),
            new ColorName(0x843179, "Plum"),
            new ColorName(0x84A0A0, "Granny Smith"),
            new ColorName(0x8581D9, "Chetwode Blue"),
            new ColorName(0x858470, "Bandicoot"),
            new ColorName(0x859FAF, "Bali Hai"),
            new ColorName(0x85C4CC, "Half Baked"),
            new ColorName(0x860111, "Red Devil"),
            new ColorName(0x863C3C, "Lotus"),
            new ColorName(0x86483C, "Ironstone"),
            new ColorName(0x864D1E, "Bull Shot"),
            new ColorName(0x86560A, "Rusty Nail"),
            new ColorName(0x868974, "Bitter"),
            new ColorName(0x86949F, "Regent Gray"),
            new ColorName(0x871550, "Disco"),
            new ColorName(0x87756E, "Americano"),
            new ColorName(0x877C7B, "Hurricane"),
            new ColorName(0x878D91, "Oslo Gray"),
            new ColorName(0x87AB39, "Sushi"),
            new ColorName(0x885342, "Spicy Mix"),
            new ColorName(0x886221, "Kumera"),
            new ColorName(0x888387, "Suva Gray"),
            new ColorName(0x888D65, "Avocado"),
            new ColorName(0x893456, "Camelot"),
            new ColorName(0x893843, "Solid Pink"),
            new ColorName(0x894367, "Cannon Pink"),
            new ColorName(0x897D6D, "Makara"),
            new ColorName(0x8A3324, "Burnt Umber"),
            new ColorName(0x8A73D6, "True V"),
            new ColorName(0x8A8360, "Clay Creek"),
            new ColorName(0x8A8389, "Monsoon"),
            new ColorName(0x8A8F8A, "Stack"),
            new ColorName(0x8AB9F1, "Jordy Blue"),
            new ColorName(0x8B00FF, "Electric Violet"),
            new ColorName(0x8B0723, "Monarch"),
            new ColorName(0x8B6B0B, "Corn Harvest"),
            new ColorName(0x8B8470, "Olive Haze"),
            new ColorName(0x8B847E, "Schooner"),
            new ColorName(0x8B8680, "Natural Gray"),
            new ColorName(0x8B9C90, "Mantle"),
            new ColorName(0x8B9FEE, "Portage"),
            new ColorName(0x8BA690, "Envy"),
            new ColorName(0x8BA9A5, "Cascade"),
            new ColorName(0x8BE6D8, "Riptide"),
            new ColorName(0x8C055E, "Cardinal Pink"),
            new ColorName(0x8C472F, "Mule Fawn"),
            new ColorName(0x8C5738, "Potters Clay"),
            new ColorName(0x8C6495, "Trendy Pink"),
            new ColorName(0x8D0226, "Paprika"),
            new ColorName(0x8D3D38, "Sanguine Brown"),
            new ColorName(0x8D3F3F, "Tosca"),
            new ColorName(0x8D7662, "Cement"),
            new ColorName(0x8D8974, "Granite Green"),
            new ColorName(0x8D90A1, "Manatee"),
            new ColorName(0x8DA8CC, "Polo Blue"),
            new ColorName(0x8E0000, "Red Berry"),
            new ColorName(0x8E4D1E, "Rope"),
            new ColorName(0x8E6F70, "Opium"),
            new ColorName(0x8E775E, "Domino"),
            new ColorName(0x8E8190, "Mamba"),
            new ColorName(0x8EABC1, "Nepal"),
            new ColorName(0x8F021C, "Pohutukawa"),
            new ColorName(0x8F3E33, "El Salva"),
            new ColorName(0x8F4B0E, "Korma"),
            new ColorName(0x8F8176, "Squirrel"),
            new ColorName(0x8FD6B4, "Vista Blue"),
            new ColorName(0x900020, "Burgundy"),
            new ColorName(0x901E1E, "Old Brick"),
            new ColorName(0x907874, "Hemp"),
            new ColorName(0x907B71, "Almond Frost"),
            new ColorName(0x908D39, "Sycamore"),
            new ColorName(0x92000A, "Sangria"),
            new ColorName(0x924321, "Cumin"),
            new ColorName(0x926F5B, "Beaver"),
            new ColorName(0x928573, "Stonewall"),
            new ColorName(0x928590, "Venus"),
            new ColorName(0x9370DB, "Medium Purple"),
            new ColorName(0x93CCEA, "Cornflower"),
            new ColorName(0x93DFB8, "Algae Green"),
            new ColorName(0x944747, "Copper Rust"),
            new ColorName(0x948771, "Arrowtown"),
            new ColorName(0x950015, "Scarlett"),
            new ColorName(0x956387, "Strikemaster"),
            new ColorName(0x959396, "Mountain Mist"),
            new ColorName(0x960018, "Carmine"),
            new ColorName(0x964B00, "Brown"),
            new ColorName(0x967059, "Leather"),
            new ColorName(0x9678B6, "Purple Mountain's Majesty"),
            new ColorName(0x967BB6, "Lavender Purple"),
            new ColorName(0x96A8A1, "Pewter"),
            new ColorName(0x96BBAB, "Summer Green"),
            new ColorName(0x97605D, "Au Chico"),
            new ColorName(0x9771B5, "Wisteria"),
            new ColorName(0x97CD2D, "Atlantis"),
            new ColorName(0x983D61, "Vin Rouge"),
            new ColorName(0x9874D3, "Lilac Bush"),
            new ColorName(0x98777B, "Bazaar"),
            new ColorName(0x98811B, "Hacienda"),
            new ColorName(0x988D77, "Pale Oyster"),
            new ColorName(0x98FF98, "Mint Green"),
            new ColorName(0x990066, "Fresh Eggplant"),
            new ColorName(0x991199, "Violet Eggplant"),
            new ColorName(0x991613, "Tamarillo"),
            new ColorName(0x991B07, "Totem Pole"),
            new ColorName(0x996666, "Copper Rose"),
            new ColorName(0x9966CC, "Amethyst"),
            new ColorName(0x997A8D, "Mountbatten Pink"),
            new ColorName(0x9999CC, "Blue Bell"),
            new ColorName(0x9A3820, "Prairie Sand"),
            new ColorName(0x9A6E61, "Toast"),
            new ColorName(0x9A9577, "Gurkha"),
            new ColorName(0x9AB973, "Olivine"),
            new ColorName(0x9AC2B8, "Shadow Green"),
            new ColorName(0x9B4703, "Oregon"),
            new ColorName(0x9B9E8F, "Lemon Grass"),
            new ColorName(0x9C3336, "Stiletto"),
            new ColorName(0x9D5616, "Hawaiian Tan"),
            new ColorName(0x9DACB7, "Gull Gray"),
            new ColorName(0x9DC209, "Pistachio"),
            new ColorName(0x9DE093, "Granny Smith Apple"),
            new ColorName(0x9DE5FF, "Anakiwa"),
            new ColorName(0x9E5302, "Chelsea Gem"),
            new ColorName(0x9E5B40, "Sepia Skin"),
            new ColorName(0x9EA587, "Sage"),
            new ColorName(0x9EA91F, "Citron"),
            new ColorName(0x9EB1CD, "Rock Blue"),
            new ColorName(0x9EDEE0, "Morning Glory"),
            new ColorName(0x9F381D, "Cognac"),
            new ColorName(0x9F821C, "Reef Gold"),
            new ColorName(0x9F9F9C, "Star Dust"),
            new ColorName(0x9FA0B1, "Santas Gray"),
            new ColorName(0x9FD7D3, "Sinbad"),
            new ColorName(0x9FDD8C, "Feijoa"),
            new ColorName(0xA02712, "Tabasco"),
            new ColorName(0xA1750D, "Buttered Rum"),
            new ColorName(0xA1ADB5, "Hit Gray"),
            new ColorName(0xA1C50A, "Citrus"),
            new ColorName(0xA1DAD7, "Aqua Island"),
            new ColorName(0xA1E9DE, "Water Leaf"),
            new ColorName(0xA2006D, "Flirt"),
            new ColorName(0xA23B6C, "Rouge"),
            new ColorName(0xA26645, "Cape Palliser"),
            new ColorName(0xA2AAB3, "Gray Chateau"),
            new ColorName(0xA2AEAB, "Edward"),
            new ColorName(0xA3807B, "Pharlap"),
            new ColorName(0xA397B4, "Amethyst Smoke"),
            new ColorName(0xA3E3ED, "Blizzard Blue"),
            new ColorName(0xA4A49D, "Delta"),
            new ColorName(0xA4A6D3, "Wistful"),
            new ColorName(0xA4AF6E, "Green Smoke"),
            new ColorName(0xA50B5E, "Jazzberry Jam"),
            new ColorName(0xA59B91, "Zorba"),
            new ColorName(0xA5CB0C, "Bahia"),
            new ColorName(0xA62F20, "Roof Terracotta"),
            new ColorName(0xA65529, "Paarl"),
            new ColorName(0xA68B5B, "Barley Corn"),
            new ColorName(0xA69279, "Donkey Brown"),
            new ColorName(0xA6A29A, "Dawn"),
            new ColorName(0xA72525, "Mexican Red"),
            new ColorName(0xA7882C, "Luxor Gold"),
            new ColorName(0xA85307, "Rich Gold"),
            new ColorName(0xA86515, "Reno Sand"),
            new ColorName(0xA86B6B, "Coral Tree"),
            new ColorName(0xA8989B, "Dusty Gray"),
            new ColorName(0xA899E6, "Dull Lavender"),
            new ColorName(0xA8A589, "Tallow"),
            new ColorName(0xA8AE9C, "Bud"),
            new ColorName(0xA8AF8E, "Locust"),
            new ColorName(0xA8BD9F, "Norway"),
            new ColorName(0xA8E3BD, "Chinook"),
            new ColorName(0xA9A491, "Gray Olive"),
            new ColorName(0xA9ACB6, "Aluminium"),
            new ColorName(0xA9B2C3, "Cadet Blue"),
            new ColorName(0xA9B497, "Schist"),
            new ColorName(0xA9BDBF, "Tower Gray"),
            new ColorName(0xA9BEF2, "Perano"),
            new ColorName(0xA9C6C2, "Opal"),
            new ColorName(0xAA375A, "Night Shadz"),
            new ColorName(0xAA4203, "Fire"),
            new ColorName(0xAA8B5B, "Muesli"),
            new ColorName(0xAA8D6F, "Sandal"),
            new ColorName(0xAAA5A9, "Shady Lady"),
            new ColorName(0xAAA9CD, "Logan"),
            new ColorName(0xAAABB7, "Spun Pearl"),
            new ColorName(0xAAD6E6, "Regent St Blue"),
            new ColorName(0xAAF0D1, "Magic Mint"),
            new ColorName(0xAB0563, "Lipstick"),
            new ColorName(0xAB3472, "Royal Heath"),
            new ColorName(0xAB917A, "Sandrift"),
            new ColorName(0xABA0D9, "Cold Purple"),
            new ColorName(0xABA196, "Bronco"),
            new ColorName(0xAC8A56, "Limed Oak"),
            new ColorName(0xAC91CE, "East Side"),
            new ColorName(0xAC9E22, "Lemon Ginger"),
            new ColorName(0xACA494, "Napa"),
            new ColorName(0xACA586, "Hillary"),
            new ColorName(0xACA59F, "Cloudy"),
            new ColorName(0xACACAC, "Silver Chalice"),
            new ColorName(0xACB78E, "Swamp Green"),
            new ColorName(0xACCBB1, "Spring Rain"),
            new ColorName(0xACDD4D, "Conifer"),
            new ColorName(0xACE1AF, "Celadon"),
            new ColorName(0xAD781B, "Mandalay"),
            new ColorName(0xADBED1, "Casper"),
            new ColorName(0xADDFAD, "Moss Green"),
            new ColorName(0xADE6C4, "Padua"),
            new ColorName(0xADFF2F, "Green Yellow"),
            new ColorName(0xAE4560, "Hippie Pink"),
            new ColorName(0xAE6020, "Desert"),
            new ColorName(0xAE809E, "Bouquet"),
            new ColorName(0xAF4035, "Medium Carmine"),
            new ColorName(0xAF4D43, "Apple Blossom"),
            new ColorName(0xAF593E, "Brown Rust"),
            new ColorName(0xAF8751, "Driftwood"),
            new ColorName(0xAF8F2C, "Alpine"),
            new ColorName(0xAF9F1C, "Lucky"),
            new ColorName(0xAFA09E, "Martini"),
            new ColorName(0xAFB1B8, "Bombay"),
            new ColorName(0xAFBDD9, "Pigeon Post"),
            new ColorName(0xB04C6A, "Cadillac"),
            new ColorName(0xB05D54, "Matrix"),
            new ColorName(0xB05E81, "Tapestry"),
            new ColorName(0xB06608, "Mai Tai"),
            new ColorName(0xB09A95, "Del Rio"),
            new ColorName(0xB0E0E6, "Powder Blue"),
            new ColorName(0xB0E313, "Inch Worm"),
            new ColorName(0xB10000, "Bright Red"),
            new ColorName(0xB14A0B, "Vesuvius"),
            new ColorName(0xB1610B, "Pumpkin Skin"),
            new ColorName(0xB16D52, "Santa Fe"),
            new ColorName(0xB19461, "Teak"),
            new ColorName(0xB1E2C1, "Fringy Flower"),
            new ColorName(0xB1F4E7, "Ice Cold"),
            new ColorName(0xB20931, "Shiraz"),
            new ColorName(0xB2A1EA, "Biloba Flower"),
            new ColorName(0xB32D29, "Tall Poppy"),
            new ColorName(0xB35213, "Fiery Orange"),
            new ColorName(0xB38007, "Hot Toddy"),
            new ColorName(0xB3AF95, "Taupe Gray"),
            new ColorName(0xB3C110, "La Rioja"),
            new ColorName(0xB43332, "Well Read"),
            new ColorName(0xB44668, "Blush"),
            new ColorName(0xB4CFD3, "Jungle Mist"),
            new ColorName(0xB57281, "Turkish Rose"),
            new ColorName(0xB57EDC, "Lavender"),
            new ColorName(0xB5A27F, "Mongoose"),
            new ColorName(0xB5B35C, "Olive Green"),
            new ColorName(0xB5D2CE, "Jet Stream"),
            new ColorName(0xB5ECDF, "Cruise"),
            new ColorName(0xB6316C, "Hibiscus"),
            new ColorName(0xB69D98, "Thatch"),
            new ColorName(0xB6B095, "Heathered Gray"),
            new ColorName(0xB6BAA4, "Eagle"),
            new ColorName(0xB6D1EA, "Spindle"),
            new ColorName(0xB6D3BF, "Gum Leaf"),
            new ColorName(0xB7410E, "Rust"),
            new ColorName(0xB78E5C, "Muddy Waters"),
            new ColorName(0xB7A214, "Sahara"),
            new ColorName(0xB7A458, "Husk"),
            new ColorName(0xB7B1B1, "Nobel"),
            new ColorName(0xB7C3D0, "Heather"),
            new ColorName(0xB7F0BE, "Madang"),
            new ColorName(0xB81104, "Milano Red"),
            new ColorName(0xB87333, "Copper"),
            new ColorName(0xB8B56A, "Gimblet"),
            new ColorName(0xB8C1B1, "Green Spring"),
            new ColorName(0xB8C25D, "Celery"),
            new ColorName(0xB8E0F9, "Sail"),
            new ColorName(0xB94E48, "Chestnut"),
            new ColorName(0xB95140, "Crail"),
            new ColorName(0xB98D28, "Marigold"),
            new ColorName(0xB9C46A, "Wild Willow"),
            new ColorName(0xB9C8AC, "Rainee"),
            new ColorName(0xBA0101, "Guardsman Red"),
            new ColorName(0xBA450C, "Rock Spray"),
            new ColorName(0xBA6F1E, "Bourbon"),
            new ColorName(0xBA7F03, "Pirate Gold"),
            new ColorName(0xBAB1A2, "Nomad"),
            new ColorName(0xBAC7C9, "Submarine"),
            new ColorName(0xBAEEF9, "Charlotte"),
            new ColorName(0xBB3385, "Medium Red Violet"),
            new ColorName(0xBB8983, "Brandy Rose"),
            new ColorName(0xBBD009, "Rio Grande"),
            new ColorName(0xBBD7C1, "Surf"),
            new ColorName(0xBCC9C2, "Powder Ash"),
            new ColorName(0xBD5E2E, "Tuscany"),
            new ColorName(0xBD978E, "Quicksand"),
            new ColorName(0xBDB1A8, "Silk"),
            new ColorName(0xBDB2A1, "Malta"),
            new ColorName(0xBDB3C7, "Chatelle"),
            new ColorName(0xBDBBD7, "Lavender Gray"),
            new ColorName(0xBDBDC6, "French Gray"),
            new ColorName(0xBDC8B3, "Clay Ash"),
            new ColorName(0xBDC9CE, "Loblolly"),
            new ColorName(0xBDEDFD, "French Pass"),
            new ColorName(0xBEA6C3, "London Hue"),
            new ColorName(0xBEB5B7, "Pink Swan"),
            new ColorName(0xBEDE0D, "Fuego"),
            new ColorName(0xBF5500, "Rose of Sharon"),
            new ColorName(0xBFB8B0, "Tide"),
            new ColorName(0xBFBED8, "Blue Haze"),
            new ColorName(0xBFC1C2, "Silver Sand"),
            new ColorName(0xBFC921, "Key Lime Pie"),
            new ColorName(0xBFDBE2, "Ziggurat"),
            new ColorName(0xBFFF00, "Lime"),
            new ColorName(0xC02B18, "Thunderbird"),
            new ColorName(0xC04737, "Mojo"),
            new ColorName(0xC08081, "Old Rose"),
            new ColorName(0xC0C0C0, "Silver"),
            new ColorName(0xC0D3B9, "Pale Leaf"),
            new ColorName(0xC0D8B6, "Pixie Green"),
            new ColorName(0xC1440E, "Tia Maria"),
            new ColorName(0xC154C1, "Fuchsia Pink"),
            new ColorName(0xC1A004, "Buddha Gold"),
            new ColorName(0xC1B7A4, "Bison Hide"),
            new ColorName(0xC1BAB0, "Tea"),
            new ColorName(0xC1BECD, "Gray Suit"),
            new ColorName(0xC1D7B0, "Sprout"),
            new ColorName(0xC1F07C, "Sulu"),
            new ColorName(0xC26B03, "Indochine"),
            new ColorName(0xC2955D, "Twine"),
            new ColorName(0xC2BDB6, "Cotton Seed"),
            new ColorName(0xC2CAC4, "Pumice"),
            new ColorName(0xC2E8E5, "Jagged Ice"),
            new ColorName(0xC32148, "Maroon Flush"),
            new ColorName(0xC3B091, "Indian Khaki"),
            new ColorName(0xC3BFC1, "Pale Slate"),
            new ColorName(0xC3C3BD, "Gray Nickel"),
            new ColorName(0xC3CDE6, "Periwinkle Gray"),
            new ColorName(0xC3D1D1, "Tiara"),
            new ColorName(0xC3DDF9, "Tropical Blue"),
            new ColorName(0xC41E3A, "Cardinal"),
            new ColorName(0xC45655, "Fuzzy Wuzzy Brown"),
            new ColorName(0xC45719, "Orange Roughy"),
            new ColorName(0xC4C4BC, "Mist Gray"),
            new ColorName(0xC4D0B0, "Coriander"),
            new ColorName(0xC4F4EB, "Mint Tulip"),
            new ColorName(0xC54B8C, "Mulberry"),
            new ColorName(0xC59922, "Nugget"),
            new ColorName(0xC5994B, "Tussock"),
            new ColorName(0xC5DBCA, "Sea Mist"),
            new ColorName(0xC5E17A, "Yellow Green"),
            new ColorName(0xC62D42, "Brick Red"),
            new ColorName(0xC6726B, "Contessa"),
            new ColorName(0xC69191, "Oriental Pink"),
            new ColorName(0xC6A84B, "Roti"),
            new ColorName(0xC6C3B5, "Ash"),
            new ColorName(0xC6C8BD, "Kangaroo"),
            new ColorName(0xC6E610, "Las Palmas"),
            new ColorName(0xC7031E, "Monza"),
            new ColorName(0xC71585, "Red Violet"),
            new ColorName(0xC7BCA2, "Coral Reef"),
            new ColorName(0xC7C1FF, "Melrose"),
            new ColorName(0xC7C4BF, "Cloud"),
            new ColorName(0xC7C9D5, "Ghost"),
            new ColorName(0xC7CD90, "Pine Glade"),
            new ColorName(0xC7DDE5, "Botticelli"),
            new ColorName(0xC88A65, "Antique Brass"),
            new ColorName(0xC8A2C8, "Lilac"),
            new ColorName(0xC8A528, "Hokey Pokey"),
            new ColorName(0xC8AABF, "Lily"),
            new ColorName(0xC8B568, "Laser"),
            new ColorName(0xC8E3D7, "Edgewater"),
            new ColorName(0xC96323, "Piper"),
            new ColorName(0xC99415, "Pizza"),
            new ColorName(0xC9A0DC, "Light Wisteria"),
            new ColorName(0xC9B29B, "Rodeo Dust"),
            new ColorName(0xC9B35B, "Sundance"),
            new ColorName(0xC9B93B, "Earls Green"),
            new ColorName(0xC9C0BB, "Silver Rust"),
            new ColorName(0xC9D9D2, "Conch"),
            new ColorName(0xC9FFA2, "Reef"),
            new ColorName(0xC9FFE5, "Aero Blue"),
            new ColorName(0xCA3435, "Flush Mahogany"),
            new ColorName(0xCABB48, "Turmeric"),
            new ColorName(0xCADCD4, "Paris White"),
            new ColorName(0xCAE00D, "Bitter Lemon"),
            new ColorName(0xCAE6DA, "Skeptic"),
            new ColorName(0xCB8FA9, "Viola"),
            new ColorName(0xCBCAB6, "Foggy Gray"),
            new ColorName(0xCBD3B0, "Green Mist"),
            new ColorName(0xCBDBD6, "Nebula"),
            new ColorName(0xCC3333, "Persian Red"),
            new ColorName(0xCC5500, "Burnt Orange"),
            new ColorName(0xCC7722, "Ochre"),
            new ColorName(0xCC8899, "Puce"),
            new ColorName(0xCCCAA8, "Thistle Green"),
            new ColorName(0xCCCCFF, "Periwinkle"),
            new ColorName(0xCCFF00, "Electric Lime"),
            new ColorName(0xCD5700, "Tenn"),
            new ColorName(0xCD5C5C, "Chestnut Rose"),
            new ColorName(0xCD8429, "Brandy Punch"),
            new ColorName(0xCDF4FF, "Onahau"),
            new ColorName(0xCEB98F, "Sorrell Brown"),
            new ColorName(0xCEBABA, "Cold Turkey"),
            new ColorName(0xCEC291, "Yuma"),
            new ColorName(0xCEC7A7, "Chino"),
            new ColorName(0xCFA39D, "Eunry"),
            new ColorName(0xCFB53B, "Old Gold"),
            new ColorName(0xCFDCCF, "Tasman"),
            new ColorName(0xCFE5D2, "Surf Crest"),
            new ColorName(0xCFF9F3, "Humming Bird"),
            new ColorName(0xCFFAF4, "Scandal"),
            new ColorName(0xD05F04, "Red Stage"),
            new ColorName(0xD06DA1, "Hopbush"),
            new ColorName(0xD07D12, "Meteor"),
            new ColorName(0xD0BEF8, "Perfume"),
            new ColorName(0xD0C0E5, "Prelude"),
            new ColorName(0xD0F0C0, "Tea Green"),
            new ColorName(0xD18F1B, "Geebung"),
            new ColorName(0xD1BEA8, "Vanilla"),
            new ColorName(0xD1C6B4, "Soft Amber"),
            new ColorName(0xD1D2CA, "Celeste"),
            new ColorName(0xD1D2DD, "Mischka"),
            new ColorName(0xD1E231, "Pear"),
            new ColorName(0xD2691E, "Hot Cinnamon"),
            new ColorName(0xD27D46, "Raw Sienna"),
            new ColorName(0xD29EAA, "Careys Pink"),
            new ColorName(0xD2B48C, "Tan"),
            new ColorName(0xD2DA97, "Deco"),
            new ColorName(0xD2F6DE, "Blue Romance"),
            new ColorName(0xD2F8B0, "Gossip"),
            new ColorName(0xD3CBBA, "Sisal"),
            new ColorName(0xD3CDC5, "Swirl"),
            new ColorName(0xD47494, "Charm"),
            new ColorName(0xD4B6AF, "Clam Shell"),
            new ColorName(0xD4BF8D, "Straw"),
            new ColorName(0xD4C4A8, "Akaroa"),
            new ColorName(0xD4CD16, "Bird Flower"),
            new ColorName(0xD4D7D9, "Iron"),
            new ColorName(0xD4DFE2, "Geyser"),
            new ColorName(0xD4E2FC, "Hawkes Blue"),
            new ColorName(0xD54600, "Grenadier"),
            new ColorName(0xD591A4, "Can Can"),
            new ColorName(0xD59A6F, "Whiskey"),
            new ColorName(0xD5D195, "Winter Hazel"),
            new ColorName(0xD5F6E3, "Granny Apple"),
            new ColorName(0xD69188, "My Pink"),
            new ColorName(0xD6C562, "Tacha"),
            new ColorName(0xD6CEF6, "Moon Raker"),
            new ColorName(0xD6D6D1, "Quill Gray"),
            new ColorName(0xD6FFDB, "Snowy Mint"),
            new ColorName(0xD7837F, "New York Pink"),
            new ColorName(0xD7C498, "Pavlova"),
            new ColorName(0xD7D0FF, "Fog"),
            new ColorName(0xD84437, "Valencia"),
            new ColorName(0xD87C63, "Japonica"),
            new ColorName(0xD8BFD8, "Thistle"),
            new ColorName(0xD8C2D5, "Maverick"),
            new ColorName(0xD8FCFA, "Foam"),
            new ColorName(0xD94972, "Cabaret"),
            new ColorName(0xD99376, "Burning Sand"),
            new ColorName(0xD9B99B, "Cameo"),
            new ColorName(0xD9D6CF, "Timberwolf"),
            new ColorName(0xD9DCC1, "Tana"),
            new ColorName(0xD9E4F5, "Link Water"),
            new ColorName(0xD9F7FF, "Mabel"),
            new ColorName(0xDA3287, "Cerise"),
            new ColorName(0xDA5B38, "Flame Pea"),
            new ColorName(0xDA6304, "Bamboo"),
            new ColorName(0xDA6A41, "Red Damask"),
            new ColorName(0xDA70D6, "Orchid"),
            new ColorName(0xDA8A67, "Copperfield"),
            new ColorName(0xDAA520, "Golden Grass"),
            new ColorName(0xDAECD6, "Zanah"),
            new ColorName(0xDAF4F0, "Iceberg"),
            new ColorName(0xDAFAFF, "Oyster Bay"),
            new ColorName(0xDB5079, "Cranberry"),
            new ColorName(0xDB9690, "Petite Orchid"),
            new ColorName(0xDB995E, "Di Serria"),
            new ColorName(0xDBDBDB, "Alto"),
            new ColorName(0xDBFFF8, "Frosted Mint"),
            new ColorName(0xDC143C, "Crimson"),
            new ColorName(0xDC4333, "Punch"),
            new ColorName(0xDCB20C, "Galliano"),
            new ColorName(0xDCB4BC, "Blossom"),
            new ColorName(0xDCD747, "Wattle"),
            new ColorName(0xDCD9D2, "Westar"),
            new ColorName(0xDCDDCC, "Moon Mist"),
            new ColorName(0xDCEDB4, "Caper"),
            new ColorName(0xDCF0EA, "Swans Down"),
            new ColorName(0xDDD6D5, "Swiss Coffee"),
            new ColorName(0xDDF9F1, "White Ice"),
            new ColorName(0xDE3163, "Cerise Red"),
            new ColorName(0xDE6360, "Roman"),
            new ColorName(0xDEA681, "Tumbleweed"),
            new ColorName(0xDEBA13, "Gold Tips"),
            new ColorName(0xDEC196, "Brandy"),
            new ColorName(0xDECBC6, "Wafer"),
            new ColorName(0xDED4A4, "Sapling"),
            new ColorName(0xDED717, "Barberry"),
            new ColorName(0xDEE5C0, "Beryl Green"),
            new ColorName(0xDEF5FF, "Pattens Blue"),
            new ColorName(0xDF73FF, "Heliotrope"),
            new ColorName(0xDFBE6F, "Apache"),
            new ColorName(0xDFCD6F, "Chenin"),
            new ColorName(0xDFCFDB, "Lola"),
            new ColorName(0xDFECDA, "Willow Brook"),
            new ColorName(0xDFFF00, "Chartreuse Yellow"),
            new ColorName(0xE0B0FF, "Mauve"),
            new ColorName(0xE0B646, "Anzac"),
            new ColorName(0xE0B974, "Harvest Gold"),
            new ColorName(0xE0C095, "Calico"),
            new ColorName(0xE0FFFF, "Baby Blue"),
            new ColorName(0xE16865, "Sunglo"),
            new ColorName(0xE1BC64, "Equator"),
            new ColorName(0xE1C0C8, "Pink Flare"),
            new ColorName(0xE1E6D6, "Periglacial Blue"),
            new ColorName(0xE1EAD4, "Kidnapper"),
            new ColorName(0xE1F6E8, "Tara"),
            new ColorName(0xE25465, "Mandy"),
            new ColorName(0xE2725B, "Terracotta"),
            new ColorName(0xE28913, "Golden Bell"),
            new ColorName(0xE292C0, "Shocking"),
            new ColorName(0xE29418, "Dixie"),
            new ColorName(0xE29CD2, "Light Orchid"),
            new ColorName(0xE2D8ED, "Snuff"),
            new ColorName(0xE2EBED, "Mystic"),
            new ColorName(0xE2F3EC, "Apple Green"),
            new ColorName(0xE30B5C, "Razzmatazz"),
            new ColorName(0xE32636, "Alizarin Crimson"),
            new ColorName(0xE34234, "Cinnabar"),
            new ColorName(0xE3BEBE, "Cavern Pink"),
            new ColorName(0xE3F5E1, "Peppermint"),
            new ColorName(0xE3F988, "Mindaro"),
            new ColorName(0xE47698, "Deep Blush"),
            new ColorName(0xE49B0F, "Gamboge"),
            new ColorName(0xE4C2D5, "Melanie"),
            new ColorName(0xE4CFDE, "Twilight"),
            new ColorName(0xE4D1C0, "Bone"),
            new ColorName(0xE4D422, "Sunflower"),
            new ColorName(0xE4D5B7, "Grain Brown"),
            new ColorName(0xE4D69B, "Zombie"),
            new ColorName(0xE4F6E7, "Frostee"),
            new ColorName(0xE4FFD1, "Snow Flurry"),
            new ColorName(0xE52B50, "Amaranth"),
            new ColorName(0xE5841B, "Zest"),
            new ColorName(0xE5CCC9, "Dust Storm"),
            new ColorName(0xE5D7BD, "Stark White"),
            new ColorName(0xE5D8AF, "Hampton"),
            new ColorName(0xE5E0E1, "Bon Jour"),
            new ColorName(0xE5E5E5, "Mercury"),
            new ColorName(0xE5F9F6, "Polar"),
            new ColorName(0xE64E03, "Trinidad"),
            new ColorName(0xE6BE8A, "Gold Sand"),
            new ColorName(0xE6BEA5, "Cashmere"),
            new ColorName(0xE6D7B9, "Double Spanish White"),
            new ColorName(0xE6E4D4, "Satin Linen"),
            new ColorName(0xE6F2EA, "Harp"),
            new ColorName(0xE6F8F3, "Off Green"),
            new ColorName(0xE6FFE9, "Hint of Green"),
            new ColorName(0xE6FFFF, "Tranquil"),
            new ColorName(0xE77200, "Mango Tango"),
            new ColorName(0xE7730A, "Christine"),
            new ColorName(0xE79F8C, "Tonys Pink"),
            new ColorName(0xE79FC4, "Kobi"),
            new ColorName(0xE7BCB4, "Rose Fog"),
            new ColorName(0xE7BF05, "Corn"),
            new ColorName(0xE7CD8C, "Putty"),
            new ColorName(0xE7ECE6, "Gray Nurse"),
            new ColorName(0xE7F8FF, "Lily White"),
            new ColorName(0xE7FEFF, "Bubbles"),
            new ColorName(0xE89928, "Fire Bush"),
            new ColorName(0xE8B9B3, "Shilo"),
            new ColorName(0xE8E0D5, "Pearl Bush"),
            new ColorName(0xE8EBE0, "Green White"),
            new ColorName(0xE8F1D4, "Chrome White"),
            new ColorName(0xE8F2EB, "Gin"),
            new ColorName(0xE8F5F2, "Aqua Squeeze"),
            new ColorName(0xE96E00, "Clementine"),
            new ColorName(0xE97451, "Burnt Sienna"),
            new ColorName(0xE97C07, "Tahiti Gold"),
            new ColorName(0xE9CECD, "Oyster Pink"),
            new ColorName(0xE9D75A, "Confetti"),
            new ColorName(0xE9E3E3, "Ebb"),
            new ColorName(0xE9F8ED, "Ottoman"),
            new ColorName(0xE9FFFD, "Clear Day"),
            new ColorName(0xEA88A8, "Carissma"),
            new ColorName(0xEAAE69, "Porsche"),
            new ColorName(0xEAB33B, "Tulip Tree"),
            new ColorName(0xEAC674, "Rob Roy"),
            new ColorName(0xEADAB8, "Raffia"),
            new ColorName(0xEAE8D4, "White Rock"),
            new ColorName(0xEAF6EE, "Panache"),
            new ColorName(0xEAF6FF, "Solitude"),
            new ColorName(0xEAF9F5, "Aqua Spring"),
            new ColorName(0xEAFFFE, "Dew"),
            new ColorName(0xEB9373, "Apricot"),
            new ColorName(0xEBC2AF, "Zinnwaldite"),
            new ColorName(0xECA927, "Fuel Yellow"),
            new ColorName(0xECC54E, "Ronchi"),
            new ColorName(0xECC7EE, "French Lilac"),
            new ColorName(0xECCDB9, "Just Right"),
            new ColorName(0xECE090, "Wild Rice"),
            new ColorName(0xECEBBD, "Fall Green"),
            new ColorName(0xECEBCE, "Aths Special"),
            new ColorName(0xECF245, "Starship"),
            new ColorName(0xED0A3F, "Red Ribbon"),
            new ColorName(0xED7A1C, "Tango"),
            new ColorName(0xED9121, "Carrot Orange"),
            new ColorName(0xED989E, "Sea Pink"),
            new ColorName(0xEDB381, "Tacao"),
            new ColorName(0xEDC9AF, "Desert Sand"),
            new ColorName(0xEDCDAB, "Pancho"),
            new ColorName(0xEDDCB1, "Chamois"),
            new ColorName(0xEDEA99, "Primrose"),
            new ColorName(0xEDF5DD, "Frost"),
            new ColorName(0xEDF5F5, "Aqua Haze"),
            new ColorName(0xEDF6FF, "Zumthor"),
            new ColorName(0xEDF9F1, "Narvik"),
            new ColorName(0xEDFC84, "Honeysuckle"),
            new ColorName(0xEE82EE, "Lavender Magenta"),
            new ColorName(0xEEC1BE, "Beauty Bush"),
            new ColorName(0xEED794, "Chalky"),
            new ColorName(0xEED9C4, "Almond"),
            new ColorName(0xEEDC82, "Flax"),
            new ColorName(0xEEDEDA, "Bizarre"),
            new ColorName(0xEEE3AD, "Double Colonial White"),
            new ColorName(0xEEEEE8, "Cararra"),
            new ColorName(0xEEEF78, "Manz"),
            new ColorName(0xEEF0C8, "Tahuna Sands"),
            new ColorName(0xEEF0F3, "Athens Gray"),
            new ColorName(0xEEF3C3, "Tusk"),
            new ColorName(0xEEF4DE, "Loafer"),
            new ColorName(0xEEF6F7, "Catskill White"),
            new ColorName(0xEEFDFF, "Twilight Blue"),
            new ColorName(0xEEFF9A, "Jonquil"),
            new ColorName(0xEEFFE2, "Rice Flower"),
            new ColorName(0xEF863F, "Jaffa"),
            new ColorName(0xEFEFEF, "Gallery"),
            new ColorName(0xEFF2F3, "Porcelain"),
            new ColorName(0xF091A9, "Mauvelous"),
            new ColorName(0xF0D52D, "Golden Dream"),
            new ColorName(0xF0DB7D, "Golden Sand"),
            new ColorName(0xF0DC82, "Buff"),
            new ColorName(0xF0E2EC, "Prim"),
            new ColorName(0xF0E68C, "Khaki"),
            new ColorName(0xF0EEFD, "Selago"),
            new ColorName(0xF0EEFF, "Titan White"),
            new ColorName(0xF0F8FF, "Alice Blue"),
            new ColorName(0xF0FCEA, "Feta"),
            new ColorName(0xF18200, "Gold Drop"),
            new ColorName(0xF19BAB, "Wewak"),
            new ColorName(0xF1E788, "Sahara Sand"),
            new ColorName(0xF1E9D2, "Parchment"),
            new ColorName(0xF1E9FF, "Blue Chalk"),
            new ColorName(0xF1EEC1, "Mint Julep"),
            new ColorName(0xF1F1F1, "Seashell"),
            new ColorName(0xF1F7F2, "Saltpan"),
            new ColorName(0xF1FFAD, "Tidal"),
            new ColorName(0xF1FFC8, "Chiffon"),
            new ColorName(0xF2552A, "Flamingo"),
            new ColorName(0xF28500, "Tangerine"),
            new ColorName(0xF2C3B2, "Mandys Pink"),
            new ColorName(0xF2F2F2, "Concrete"),
            new ColorName(0xF2FAFA, "Black Squeeze"),
            new ColorName(0xF34723, "Pomegranate"),
            new ColorName(0xF3AD16, "Buttercup"),
            new ColorName(0xF3D69D, "New Orleans"),
            new ColorName(0xF3D9DF, "Vanilla Ice"),
            new ColorName(0xF3E7BB, "Sidecar"),
            new ColorName(0xF3E9E5, "Dawn Pink"),
            new ColorName(0xF3EDCF, "Wheatfield"),
            new ColorName(0xF3FB62, "Canary"),
            new ColorName(0xF3FBD4, "Orinoco"),
            new ColorName(0xF3FFD8, "Carla"),
            new ColorName(0xF400A1, "Hollywood Cerise"),
            new ColorName(0xF4A460, "Sandy brown"),
            new ColorName(0xF4C430, "Saffron"),
            new ColorName(0xF4D81C, "Ripe Lemon"),
            new ColorName(0xF4EBD3, "Janna"),
            new ColorName(0xF4F2EE, "Pampas"),
            new ColorName(0xF4F4F4, "Wild Sand"),
            new ColorName(0xF4F8FF, "Zircon"),
            new ColorName(0xF57584, "Froly"),
            new ColorName(0xF5C85C, "Cream Can"),
            new ColorName(0xF5C999, "Manhattan"),
            new ColorName(0xF5D5A0, "Maize"),
            new ColorName(0xF5DEB3, "Wheat"),
            new ColorName(0xF5E7A2, "Sandwisp"),
            new ColorName(0xF5E7E2, "Pot Pourri"),
            new ColorName(0xF5E9D3, "Albescent White"),
            new ColorName(0xF5EDEF, "Soft Peach"),
            new ColorName(0xF5F3E5, "Ecru White"),
            new ColorName(0xF5F5DC, "Beige"),
            new ColorName(0xF5FB3D, "Golden Fizz"),
            new ColorName(0xF5FFBE, "Australian Mint"),
            new ColorName(0xF64A8A, "French Rose"),
            new ColorName(0xF653A6, "Brilliant Rose"),
            new ColorName(0xF6A4C9, "Illusion"),
            new ColorName(0xF6F0E6, "Merino"),
            new ColorName(0xF6F7F7, "Black Haze"),
            new ColorName(0xF6FFDC, "Spring Sun"),
            new ColorName(0xF7468A, "Violet Red"),
            new ColorName(0xF77703, "Chilean Fire"),
            new ColorName(0xF77FBE, "Persian Pink"),
            new ColorName(0xF7B668, "Rajah"),
            new ColorName(0xF7C8DA, "Azalea"),
            new ColorName(0xF7DBE6, "We Peep"),
            new ColorName(0xF7F2E1, "Quarter Spanish White"),
            new ColorName(0xF7F5FA, "Whisper"),
            new ColorName(0xF7FAF7, "Snow Drift"),
            new ColorName(0xF8B853, "Casablanca"),
            new ColorName(0xF8C3DF, "Chantilly"),
            new ColorName(0xF8D9E9, "Cherub"),
            new ColorName(0xF8DB9D, "Marzipan"),
            new ColorName(0xF8DD5C, "Energy Yellow"),
            new ColorName(0xF8E4BF, "Givry"),
            new ColorName(0xF8F0E8, "White Linen"),
            new ColorName(0xF8F4FF, "Magnolia"),
            new ColorName(0xF8F6F1, "Spring Wood"),
            new ColorName(0xF8F7DC, "Coconut Cream"),
            new ColorName(0xF8F7FC, "White Lilac"),
            new ColorName(0xF8F8F7, "Desert Storm"),
            new ColorName(0xF8F99C, "Texas"),
            new ColorName(0xF8FACD, "Corn Field"),
            new ColorName(0xF8FDD3, "Mimosa"),
            new ColorName(0xF95A61, "Carnation"),
            new ColorName(0xF9BF58, "Saffron Mango"),
            new ColorName(0xF9E0ED, "Carousel Pink"),
            new ColorName(0xF9E4BC, "Dairy Cream"),
            new ColorName(0xF9E663, "Portica"),
            new ColorName(0xF9EAF3, "Amour"),
            new ColorName(0xF9F8E4, "Rum Swizzle"),
            new ColorName(0xF9FF8B, "Dolly"),
            new ColorName(0xF9FFF6, "Sugar Cane"),
            new ColorName(0xFA7814, "Ecstasy"),
            new ColorName(0xFA9D5A, "Tan Hide"),
            new ColorName(0xFAD3A2, "Corvette"),
            new ColorName(0xFADFAD, "Peach Yellow"),
            new ColorName(0xFAE600, "Turbo"),
            new ColorName(0xFAEAB9, "Astra"),
            new ColorName(0xFAECCC, "Champagne"),
            new ColorName(0xFAF0E6, "Linen"),
            new ColorName(0xFAF3F0, "Fantasy"),
            new ColorName(0xFAF7D6, "Citrine White"),
            new ColorName(0xFAFAFA, "Alabaster"),
            new ColorName(0xFAFDE4, "Hint of Yellow"),
            new ColorName(0xFAFFA4, "Milan"),
            new ColorName(0xFB607F, "Brink Pink"),
            new ColorName(0xFB8989, "Geraldine"),
            new ColorName(0xFBA0E3, "Lavender Rose"),
            new ColorName(0xFBA129, "Sea Buckthorn"),
            new ColorName(0xFBAC13, "Sun"),
            new ColorName(0xFBAED2, "Lavender Pink"),
            new ColorName(0xFBB2A3, "Rose Bud"),
            new ColorName(0xFBBEDA, "Cupid"),
            new ColorName(0xFBCCE7, "Classic Rose"),
            new ColorName(0xFBCEB1, "Apricot Peach"),
            new ColorName(0xFBE7B2, "Banana Mania"),
            new ColorName(0xFBE870, "Marigold Yellow"),
            new ColorName(0xFBE96C, "Festival"),
            new ColorName(0xFBEA8C, "Sweet Corn"),
            new ColorName(0xFBEC5D, "Candy Corn"),
            new ColorName(0xFBF9F9, "Hint of Red"),
            new ColorName(0xFBFFBA, "Shalimar"),
            new ColorName(0xFC0FC0, "Shocking Pink"),
            new ColorName(0xFC80A5, "Tickle Me Pink"),
            new ColorName(0xFC9C1D, "Tree Poppy"),
            new ColorName(0xFCC01E, "Lightning Yellow"),
            new ColorName(0xFCD667, "Goldenrod"),
            new ColorName(0xFCD917, "Candlelight"),
            new ColorName(0xFCDA98, "Cherokee"),
            new ColorName(0xFCF4D0, "Double Pearl Lusta"),
            new ColorName(0xFCF4DC, "Pearl Lusta"),
            new ColorName(0xFCF8F7, "Vista White"),
            new ColorName(0xFCFBF3, "Bianca"),
            new ColorName(0xFCFEDA, "Moon Glow"),
            new ColorName(0xFCFFE7, "China Ivory"),
            new ColorName(0xFCFFF9, "Ceramic"),
            new ColorName(0xFD0E35, "Torch Red"),
            new ColorName(0xFD5B78, "Wild Watermelon"),
            new ColorName(0xFD7B33, "Crusta"),
            new ColorName(0xFD7C07, "Sorbus"),
            new ColorName(0xFD9FA2, "Sweet Pink"),
            new ColorName(0xFDD5B1, "Light Apricot"),
            new ColorName(0xFDD7E4, "Pig Pink"),
            new ColorName(0xFDE1DC, "Cinderella"),
            new ColorName(0xFDE295, "Golden Glow"),
            new ColorName(0xFDE910, "Lemon"),
            new ColorName(0xFDF5E6, "Old Lace"),
            new ColorName(0xFDF6D3, "Half Colonial White"),
            new ColorName(0xFDF7AD, "Drover"),
            new ColorName(0xFDFEB8, "Pale Prim"),
            new ColorName(0xFDFFD5, "Cumulus"),
            new ColorName(0xFE28A2, "Persian Rose"),
            new ColorName(0xFE4C40, "Sunset Orange"),
            new ColorName(0xFE6F5E, "Bittersweet"),
            new ColorName(0xFE9D04, "California"),
            new ColorName(0xFEA904, "Yellow Sea"),
            new ColorName(0xFEBAAD, "Melon"),
            new ColorName(0xFED33C, "Bright Sun"),
            new ColorName(0xFED85D, "Dandelion"),
            new ColorName(0xFEDB8D, "Salomie"),
            new ColorName(0xFEE5AC, "Cape Honey"),
            new ColorName(0xFEEBF3, "Remy"),
            new ColorName(0xFEEFCE, "Oasis"),
            new ColorName(0xFEF0EC, "Bridesmaid"),
            new ColorName(0xFEF2C7, "Beeswax"),
            new ColorName(0xFEF3D8, "Bleach White"),
            new ColorName(0xFEF4CC, "Pipi"),
            new ColorName(0xFEF4DB, "Half Spanish White"),
            new ColorName(0xFEF4F8, "Wisp Pink"),
            new ColorName(0xFEF5F1, "Provincial Pink"),
            new ColorName(0xFEF7DE, "Half Dutch White"),
            new ColorName(0xFEF8E2, "Solitaire"),
            new ColorName(0xFEF8FF, "White Pointer"),
            new ColorName(0xFEF9E3, "Off Yellow"),
            new ColorName(0xFEFCED, "Orange White"),
            new ColorName(0xFF0000, "Red"),
            new ColorName(0xFF007F, "Rose"),
            new ColorName(0xFF00CC, "Purple Pizzazz"),
            new ColorName(0xFF00FF, "Magenta / Fuchsia"),
            new ColorName(0xFF2400, "Scarlet"),
            new ColorName(0xFF3399, "Wild Strawberry"),
            new ColorName(0xFF33CC, "Razzle Dazzle Rose"),
            new ColorName(0xFF355E, "Radical Red"),
            new ColorName(0xFF3F34, "Red Orange"),
            new ColorName(0xFF4040, "Coral Red"),
            new ColorName(0xFF4D00, "Vermilion"),
            new ColorName(0xFF4F00, "International Orange"),
            new ColorName(0xFF6037, "Outrageous Orange"),
            new ColorName(0xFF6600, "Blaze Orange"),
            new ColorName(0xFF66FF, "Pink Flamingo"),
            new ColorName(0xFF681F, "Orange"),
            new ColorName(0xFF69B4, "Hot Pink"),
            new ColorName(0xFF6B53, "Persimmon"),
            new ColorName(0xFF6FFF, "Blush Pink"),
            new ColorName(0xFF7034, "Burning Orange"),
            new ColorName(0xFF7518, "Pumpkin"),
            new ColorName(0xFF7D07, "Flamenco"),
            new ColorName(0xFF7F00, "Flush Orange"),
            new ColorName(0xFF7F50, "Coral"),
            new ColorName(0xFF8C69, "Salmon"),
            new ColorName(0xFF9000, "Pizazz"),
            new ColorName(0xFF910F, "West Side"),
            new ColorName(0xFF91A4, "Pink Salmon"),
            new ColorName(0xFF9933, "Neon Carrot"),
            new ColorName(0xFF9966, "Atomic Tangerine"),
            new ColorName(0xFF9980, "Vivid Tangerine"),
            new ColorName(0xFF9E2C, "Sunshade"),
            new ColorName(0xFFA000, "Orange Peel"),
            new ColorName(0xFFA194, "Mona Lisa"),
            new ColorName(0xFFA500, "Web Orange"),
            new ColorName(0xFFA6C9, "Carnation Pink"),
            new ColorName(0xFFAB81, "Hit Pink"),
            new ColorName(0xFFAE42, "Yellow Orange"),
            new ColorName(0xFFB0AC, "Cornflower Lilac"),
            new ColorName(0xFFB1B3, "Sundown"),
            new ColorName(0xFFB31F, "My Sin"),
            new ColorName(0xFFB555, "Texas Rose"),
            new ColorName(0xFFB7D5, "Cotton Candy"),
            new ColorName(0xFFB97B, "Macaroni and Cheese"),
            new ColorName(0xFFBA00, "Selective Yellow"),
            new ColorName(0xFFBD5F, "Koromiko"),
            new ColorName(0xFFBF00, "Amber"),
            new ColorName(0xFFC0A8, "Wax Flower"),
            new ColorName(0xFFC0CB, "Pink"),
            new ColorName(0xFFC3C0, "Your Pink"),
            new ColorName(0xFFC901, "Supernova"),
            new ColorName(0xFFCBA4, "Flesh"),
            new ColorName(0xFFCC33, "Sunglow"),
            new ColorName(0xFFCC5C, "Golden Tainoi"),
            new ColorName(0xFFCC99, "Peach Orange"),
            new ColorName(0xFFCD8C, "Chardonnay"),
            new ColorName(0xFFD1DC, "Pastel Pink"),
            new ColorName(0xFFD2B7, "Romantic"),
            new ColorName(0xFFD38C, "Grandis"),
            new ColorName(0xFFD700, "Gold"),
            new ColorName(0xFFD800, "School bus Yellow"),
            new ColorName(0xFFD8D9, "Cosmos"),
            new ColorName(0xFFDB58, "Mustard"),
            new ColorName(0xFFDCD6, "Peach Schnapps"),
            new ColorName(0xFFDDAF, "Caramel"),
            new ColorName(0xFFDDCD, "Tuft Bush"),
            new ColorName(0xFFDDCF, "Watusi"),
            new ColorName(0xFFDDF4, "Pink Lace"),
            new ColorName(0xFFDEAD, "Navajo White"),
            new ColorName(0xFFDEB3, "Frangipani"),
            new ColorName(0xFFE1DF, "Pippin"),
            new ColorName(0xFFE1F2, "Pale Rose"),
            new ColorName(0xFFE2C5, "Negroni"),
            new ColorName(0xFFE5A0, "Cream Brulee"),
            new ColorName(0xFFE5B4, "Peach"),
            new ColorName(0xFFE6C7, "Tequila"),
            new ColorName(0xFFE772, "Kournikova"),
            new ColorName(0xFFEAC8, "Sandy Beach"),
            new ColorName(0xFFEAD4, "Karry"),
            new ColorName(0xFFEC13, "Broom"),
            new ColorName(0xFFEDBC, "Colonial White"),
            new ColorName(0xFFEED8, "Derby"),
            new ColorName(0xFFEFA1, "Vis Vis"),
            new ColorName(0xFFEFC1, "Egg White"),
            new ColorName(0xFFEFD5, "Papaya Whip"),
            new ColorName(0xFFEFEC, "Fair Pink"),
            new ColorName(0xFFF0DB, "Peach Cream"),
            new ColorName(0xFFF0F5, "Lavender blush"),
            new ColorName(0xFFF14F, "Gorse"),
            new ColorName(0xFFF1B5, "Buttermilk"),
            new ColorName(0xFFF1D8, "Pink Lady"),
            new ColorName(0xFFF1EE, "Forget Me Not"),
            new ColorName(0xFFF1F9, "Tutu"),
            new ColorName(0xFFF39D, "Picasso"),
            new ColorName(0xFFF3F1, "Chardon"),
            new ColorName(0xFFF46E, "Paris Daisy"),
            new ColorName(0xFFF4CE, "Barley White"),
            new ColorName(0xFFF4DD, "Egg Sour"),
            new ColorName(0xFFF4E0, "Sazerac"),
            new ColorName(0xFFF4E8, "Serenade"),
            new ColorName(0xFFF4F3, "Chablis"),
            new ColorName(0xFFF5EE, "Seashell Peach"),
            new ColorName(0xFFF5F3, "Sauvignon"),
            new ColorName(0xFFF6D4, "Milk Punch"),
            new ColorName(0xFFF6DF, "Varden"),
            new ColorName(0xFFF6F5, "Rose White"),
            new ColorName(0xFFF8D1, "Baja White"),
            new ColorName(0xFFF9E2, "Gin Fizz"),
            new ColorName(0xFFF9E6, "Early Dawn"),
            new ColorName(0xFFFACD, "Lemon Chiffon"),
            new ColorName(0xFFFAF4, "Bridal Heath"),
            new ColorName(0xFFFBDC, "Scotch Mist"),
            new ColorName(0xFFFBF9, "Soapstone"),
            new ColorName(0xFFFC99, "Witch Haze"),
            new ColorName(0xFFFCEA, "Buttery White"),
            new ColorName(0xFFFCEE, "Island Spice"),
            new ColorName(0xFFFDD0, "Cream"),
            new ColorName(0xFFFDE6, "Chilean Heath"),
            new ColorName(0xFFFDE8, "Travertine"),
            new ColorName(0xFFFDF3, "Orchid White"),
            new ColorName(0xFFFDF4, "Quarter Pearl Lusta"),
            new ColorName(0xFFFEE1, "Half and Half"),
            new ColorName(0xFFFEEC, "Apricot White"),
            new ColorName(0xFFFEF0, "Rice Cake"),
            new ColorName(0xFFFEF6, "Black White"),
            new ColorName(0xFFFEFD, "Romance"),
            new ColorName(0xFFFF00, "Yellow"),
            new ColorName(0xFFFF66, "Laser Lemon"),
            new ColorName(0xFFFF99, "Pale Canary"),
            new ColorName(0xFFFFB4, "Portafino"),
            new ColorName(0xFFFFF0, "Ivory"),
            new ColorName(0xFFFFFF, "White"),
    };
}
