package cs371m.csc2726.busbuddy;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.Timestamp;
import com.google.firebase.firestore.ServerTimestamp;

public class PhotoObject implements Parcelable {
    private String uidOwner; // Server-supplied unique identifier for user
    private String photoId; // UUID identifies photo in collection and file in Firestore Storage
    private String title;
    private Timestamp timestamp; // Google timestamp, not a Java date
    PhotoObject() {}
    PhotoObject(String uidOwner, String photoId, String title) {
        this.uidOwner = uidOwner;
        this.photoId = photoId;
        this.title = title;
    }

    public String getUidOwner() {
        return uidOwner;
    }

    public String getPhotoId() {
        return photoId;
    }

    public String getTitle() {
        return title;
    }

    @ServerTimestamp
    public Timestamp getTimestamp() {
        return timestamp;
    }

    // NB: Code generated by parcelabler.com
    protected PhotoObject(Parcel in) {
        uidOwner = in.readString();
        photoId = in.readString();
        title = in.readString();
        timestamp = (Timestamp) in.readValue(Timestamp.class.getClassLoader());
        Storage store = Storage.getInstance();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(uidOwner);
        dest.writeString(photoId);
        dest.writeString(title);
        dest.writeValue(timestamp);
    }

    @SuppressWarnings("unused")
    public static final Creator<PhotoObject> CREATOR = new Creator<PhotoObject>() {
        @Override
        public PhotoObject createFromParcel(Parcel in) {
            return new PhotoObject(in);
        }

        @Override
        public PhotoObject[] newArray(int size) {
            return new PhotoObject[size];
        }
    };
}